### ISSUE TITLE
关于applealc插件

### ISSUE THREAD

**Issue by Ja1lbreakra1n** [R-a-s-c-a-l/MSI-MAG-B560M-i7-11700#1]
我想要知道怎么修改的，改了什么地方

**Comment by R-a-s-c-a-l** [comment]
Controller.plist  不过现在你不需要使用修改版了 直接用 AppleALC 1.6.7 + device-id 0D7A0000 就够了

**Comment by Ja1lbreakra1n** [comment]
我技嘉B560M-AORUS-ELITE+11400，声卡用这个没声音会死机，用你改的那个1.6.6的可以正常使用

**Comment by R-a-s-c-a-l** [comment]
这方法也不好使
<img width="259" alt="image" src="https://user-images.githubusercontent.com/78466401/145661061-77d2d6cf-e342-43f0-a5a6-70e4b8c0f111.png">
？

**Comment by Ja1lbreakra1n** [comment]
是的，放fakepciid那个输出ID66或者69声音是有的，但会出现突然死机的情况

**Comment by R-a-s-c-a-l** [comment]
用的是我发的FakePCIID ？

**Comment by Ja1lbreakra1n** [comment]
对的

**Comment by R-a-s-c-a-l** [comment]
如果用原版AppleALC 1.6.7 + device-id D07A0000 的情况是直接没有输出设备还是依旧是有输出设备 但是播放音视频进度条卡死 如果是后者你是否有确定过 device-id 是否真正的注入成功

**Comment by R-a-s-c-a-l** [comment]
请附上 注入设备属性 device-id的截图(包含设备PCI路径) 以及IORegistryExplorer的设备HDEF下的全部属性截图或者存档一份IORegistryExplorer的Dump

**Comment by R-a-s-c-a-l** [comment]
请附上 注入设备属性 device-id的截图(包含设备PCI路径) 以及IORegistryExplorer的设备HDEF下的全部属性截图或者存档一份IORegistryExplorer的Dump

**Comment by Ja1lbreakra1n** [comment]
<img width="1167" alt="截屏2021-12-12 16 14 13" src="https://user-images.githubusercontent.com/57509476/145705340-626b240d-3e0b-4c3a-98ad-9eaab6220eda.png">
<img width="1281" alt="截屏2021-12-12 16 15 21" src="https://user-images.githubusercontent.com/57509476/145705356-3c32fd02-27f4-4fde-ab79-322b7c20e721.png">

**Comment by Ja1lbreakra1n** [comment]
解决了，摆脱fakepciid死机问题
<img width="1282" alt="截屏2021-12-12 18 04 58" src="https://user-images.githubusercontent.com/57509476/145708303-d2285e1d-d11f-492d-ab81-e5a61dc0619c.png">
<img width="1285" alt="截屏2021-12-12 18 05 18" src="https://user-images.githubusercontent.com/57509476/145708308-6aa49caf-3322-48aa-940f-9e7d49f7a9c7.png">
<img width="1280" alt="截屏2021-12-12 18 09 01" src="https://user-images.githubusercontent.com/57509476/145708310-4cc7b221-b265-48f9-a010-bea6b197d69a.png">

了

**Comment by R-a-s-c-a-l** [comment]
那个AppleALC的查找替换多余了 D07A就是我给Z690推的音频控制器ID Patch  Replace就是48A3  你发的Patch适合06C8

**Comment by Ja1lbreakra1n** [comment]
我也不知道，我加了那条就可以了，而且可以丢弃fakepciid

**Comment by Ja1lbreakra1n** [comment]
请教一个问题，我的电脑第二次休眠唤醒后会重启，你有没有遇到

**Comment by R-a-s-c-a-l** [comment]
重启后开机有报告没 (要是 Sleep Wake Failure In EFI 就别发了)
